site_name: Example Documentation using MkDocs and MkDocStrings

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Example Docs using MkDocs and MkDocStrings: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md